name: Mi workflow

on: push

jobs: 
  tareas: 
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Probar codigo
        run: python3 main.py

      - name: Crear imagen docker
        run: docker build -t davyyelor/holamundo .

      - name: Probar imagen
        run: docker run davyyelor/holamundo
        
